package platform

import (
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Dandi-Pangestu/switchic/internal/agent"
	"github.com/Dandi-Pangestu/switchic/internal/rules"
	"github.com/Dandi-Pangestu/switchic/internal/util"
)

// Copilot is the platform adapter that targets GitHub Copilot cloud agent.
// Output is deterministic: same inputs always produce the same files.
type Copilot struct{}

// Name implements Adapter.
func (Copilot) Name() string { return "github-copilot" }

// Generate writes:
//   - .github/copilot-instructions.md — repository-wide context for Copilot
//   - AGENTS.md                        — root pointer to .github/copilot-instructions.md
//   - .github/agents/<name>.agent.md  — one per active agent
//   - .github/instructions/<dir>/<name>.instructions.md — one per active rule (path-specific)
//   - .github/skills/<name>/SKILL.md  — one per active skill (+ embedded extra files)
func (Copilot) Generate(ctx Context) ([]string, error) {
	var written []string

	// ── .github/copilot-instructions.md ──────────────────────────────────────
	instructionsPath := filepath.Join(ctx.Root, ".github", "copilot-instructions.md")
	instructionsContent := buildCopilotInstructions(ctx)
	if err := util.WriteFile(instructionsPath, []byte(instructionsContent)); err != nil {
		return nil, util.Wrap(err, "write %s", instructionsPath)
	}
	written = append(written, instructionsPath)

	// ── AGENTS.md ─────────────────────────────────────────────────────────────
	agentsMdPath := filepath.Join(ctx.Root, "AGENTS.md")
	agentsMdContent := buildAgentsMd()
	if err := util.WriteFile(agentsMdPath, []byte(agentsMdContent)); err != nil {
		return nil, util.Wrap(err, "write %s", agentsMdPath)
	}
	written = append(written, agentsMdPath)

	// ── .github/agents/<name>.agent.md ───────────────────────────────────────
	agentsDir := filepath.Join(ctx.Root, ".github", "agents")
	for _, a := range ctx.Agents {
		p := filepath.Join(agentsDir, a.Name+".agent.md")
		content, err := buildCopilotAgentFile(a)
		if err != nil {
			return nil, util.Wrap(err, "build copilot agent %s", a.Name)
		}
		if err := util.WriteFile(p, content); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)
	}

	// ── .github/instructions/<dir>/<name>.instructions.md ────────────────────
	instructionsDir := filepath.Join(ctx.Root, ".github", "instructions")
	for _, r := range ctx.Rules {
		p := filepath.Join(instructionsDir, r.Dir, r.Name+".instructions.md")
		content, err := buildCopilotInstructionFile(r)
		if err != nil {
			return nil, util.Wrap(err, "build copilot instruction %s", r.Name)
		}
		if err := util.WriteFile(p, content); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)
	}

	// ── .github/skills/<name>/SKILL.md ───────────────────────────────────────
	skillsDir := filepath.Join(ctx.Root, ".github", "skills")
	for _, s := range ctx.Skills {
		p := filepath.Join(skillsDir, s.Name, "SKILL.md")
		var b strings.Builder
		b.WriteString("---\n")
		fmt.Fprintf(&b, "name: %s\n", s.Name)
		if s.Description != "" {
			fmt.Fprintf(&b, "description: %s\n", collapseNewlines(s.Description))
		}
		if c := s.Copilot; c != nil {
			if c.License != "" {
				fmt.Fprintf(&b, "license: %s\n", c.License)
			}
			if c.Compatibility != "" {
				fmt.Fprintf(&b, "compatibility: %s\n", c.Compatibility)
			}
			if c.Metadata != nil {
				raw, err := yaml.Marshal(map[string]interface{}{"metadata": c.Metadata})
				if err != nil {
					return nil, util.Wrap(err, "marshal copilot skill metadata %s", s.Name)
				}
				b.Write(raw)
			}
			if c.AllowedTools != "" {
				fmt.Fprintf(&b, "allowed-tools: %s\n", c.AllowedTools)
			}
		}
		b.WriteString("---\n\n")
		if s.Prompt != "" {
			b.WriteString(s.Prompt)
			b.WriteString("\n")
		}
		if err := util.WriteFile(p, []byte(b.String())); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)

		for _, f := range s.Files {
			fp := filepath.Join(skillsDir, s.Name, f.RelPath)
			if err := util.WriteFile(fp, f.Content); err != nil {
				return nil, util.Wrap(err, "write %s", fp)
			}
			written = append(written, fp)
		}
	}

	return written, nil
}

func buildCopilotInstructions(ctx Context) string {
	var b strings.Builder
	b.WriteString(buildContextBody(ctx))
	b.WriteString("---\n\n")
	b.WriteString("_Generated by switchic — re-run `switchic switch github-copilot` to update._  \n")
	b.WriteString("_Path-specific instructions in `.github/instructions/`. Agent definitions in `.github/agents/`. Skills in `.github/skills/`._\n")
	return b.String()
}

func buildAgentsMd() string {
	var b strings.Builder
	b.WriteString("# Agents\n\n")
	b.WriteString("This repository uses AI agents managed by switchic.\n\n")
	b.WriteString("For project-wide context and GitHub Copilot instructions, see [`.github/copilot-instructions.md`](.github/copilot-instructions.md).\n\n")
	b.WriteString("Custom agents are defined in [`.github/agents/`](.github/agents/) and skills in [`.github/skills/`](.github/skills/).\n\n")
	b.WriteString("---\n\n")
	b.WriteString("_Generated by switchic — re-run `switchic switch github-copilot` to update._\n")
	return b.String()
}

// buildCopilotAgentFile renders an agent.Definition into the .agent.md content
// GitHub Copilot expects in .github/agents/<name>.agent.md.
func buildCopilotAgentFile(a agent.Definition) ([]byte, error) {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", a.Name)
	fmt.Fprintf(&b, "description: %s\n", collapseNewlines(a.Description))

	c := a.Copilot
	if c != nil {
		if len(c.Tools) > 0 {
			quoted := make([]string, len(c.Tools))
			for i, t := range c.Tools {
				quoted[i] = "'" + t + "'"
			}
			fmt.Fprintf(&b, "tools: [%s]\n", strings.Join(quoted, ", "))
		}
		if c.Target != "" {
			fmt.Fprintf(&b, "target: %s\n", c.Target)
		}
		if c.Model != "" {
			fmt.Fprintf(&b, "model: %s\n", c.Model)
		}
		if c.DisableModelInvocation {
			b.WriteString("disable-model-invocation: true\n")
		}
		if c.UserInvocable != nil && !*c.UserInvocable {
			b.WriteString("user-invocable: false\n")
		}
		if c.McpServers != nil {
			raw, err := yaml.Marshal(map[string]interface{}{"mcp-servers": c.McpServers})
			if err != nil {
				return nil, fmt.Errorf("marshal mcp-servers for %s: %w", a.Name, err)
			}
			b.Write(raw)
		}
		if len(c.Metadata) > 0 {
			raw, err := yaml.Marshal(map[string]interface{}{"metadata": c.Metadata})
			if err != nil {
				return nil, fmt.Errorf("marshal metadata for %s: %w", a.Name, err)
			}
			b.Write(raw)
		}
	}

	b.WriteString("---\n")
	if a.Instructions != "" {
		b.WriteString("\n")
		b.WriteString(a.Instructions)
		if !strings.HasSuffix(a.Instructions, "\n") {
			b.WriteString("\n")
		}
	}
	return []byte(b.String()), nil
}

// buildCopilotInstructionFile renders a rules.Definition into the .instructions.md
// content GitHub Copilot expects in .github/instructions/<name>.instructions.md.
// The applyTo pattern comes from copilot.apply-to; if absent, falls back to
// comma-joining claude.paths.
func buildCopilotInstructionFile(r rules.Definition) ([]byte, error) {
	var b strings.Builder

	applyTo := ""
	if c := r.Copilot; c != nil && c.ApplyTo != "" {
		applyTo = c.ApplyTo
	} else if c := r.Claude; c != nil && len(c.Paths) > 0 {
		applyTo = strings.Join(c.Paths, ",")
	}

	if applyTo != "" {
		b.WriteString("---\n")
		fmt.Fprintf(&b, "applyTo: %q\n", applyTo)
		if r.Copilot != nil && r.Copilot.ExcludeAgent != "" {
			fmt.Fprintf(&b, "excludeAgent: %q\n", r.Copilot.ExcludeAgent)
		}
		b.WriteString("---\n\n")
	}

	if r.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", r.Description)
	}
	if r.Content != "" {
		b.WriteString(r.Content)
		if !strings.HasSuffix(r.Content, "\n") {
			b.WriteString("\n")
		}
	}
	return []byte(b.String()), nil
}

// collapseNewlines trims trailing newlines and collapses any internal newlines
// to a single space, producing a safe single-line YAML scalar value.
func collapseNewlines(s string) string {
	s = strings.TrimRight(s, "\n")
	return strings.ReplaceAll(s, "\n", " ")
}
