package platform

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Dandi-Pangestu/switchic/internal/agent"
	"github.com/Dandi-Pangestu/switchic/internal/rules"
	"github.com/Dandi-Pangestu/switchic/internal/skill"
	"github.com/Dandi-Pangestu/switchic/internal/util"
)

// Kiro is the platform adapter that targets the Kiro CLI.
// Output is deterministic: same inputs always produce the same files.
type Kiro struct{}

// Name implements Adapter.
func (Kiro) Name() string { return "kiro" }

// Generate writes:
//   - AGENTS.md                     — main context file (AGENTS.md standard)
//   - .kiro/steering/project.md     — always-included steering pointer to AGENTS.md
//   - .kiro/agents/<name>.json      — one per active agent (Kiro JSON format)
//   - .kiro/steering/<name>.md      — one per active rule (always-included steering)
//   - .kiro/skills/<name>/SKILL.md  — one per active skill (+ embedded extra files)
func (Kiro) Generate(ctx Context) ([]string, error) {
	var written []string

	// ── AGENTS.md ─────────────────────────────────────────────────────────────
	agentsMdPath := filepath.Join(ctx.Root, "AGENTS.md")
	if err := util.WriteFile(agentsMdPath, []byte(buildKiroAgentsMd(ctx))); err != nil {
		return nil, util.Wrap(err, "write %s", agentsMdPath)
	}
	written = append(written, agentsMdPath)

	// ── .kiro/steering/project.md ─────────────────────────────────────────────
	steeringProjectPath := filepath.Join(ctx.Root, ".kiro", "steering", "project.md")
	const projectContent = "---\ninclusion: always\n---\n\n#[[file:../../AGENTS.md]]\n"
	if err := util.WriteFile(steeringProjectPath, []byte(projectContent)); err != nil {
		return nil, util.Wrap(err, "write %s", steeringProjectPath)
	}
	written = append(written, steeringProjectPath)

	// ── .kiro/agents/<name>.json ──────────────────────────────────────────────
	agentsDir := filepath.Join(ctx.Root, ".kiro", "agents")
	for _, a := range ctx.Agents {
		p := filepath.Join(agentsDir, a.Name+".json")
		content, err := buildKiroAgentFile(a)
		if err != nil {
			return nil, util.Wrap(err, "build kiro agent %s", a.Name)
		}
		if err := util.WriteFile(p, content); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)
	}

	// ── .kiro/steering/<name>.md ──────────────────────────────────────────────
	steeringDir := filepath.Join(ctx.Root, ".kiro", "steering")
	for _, r := range ctx.Rules {
		p := filepath.Join(steeringDir, r.Dir, r.Name+".md")
		content, err := buildKiroSteeringFile(r)
		if err != nil {
			return nil, util.Wrap(err, "build kiro steering %s", r.Name)
		}
		if err := util.WriteFile(p, content); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)
	}

	// ── .kiro/skills/<name>/SKILL.md ──────────────────────────────────────────
	skillsDir := filepath.Join(ctx.Root, ".kiro", "skills")
	for _, s := range ctx.Skills {
		p := filepath.Join(skillsDir, s.Name, "SKILL.md")
		content, err := buildKiroSkillFile(s)
		if err != nil {
			return nil, util.Wrap(err, "build kiro skill %s", s.Name)
		}
		if err := util.WriteFile(p, []byte(content)); err != nil {
			return nil, util.Wrap(err, "write %s", p)
		}
		written = append(written, p)

		for _, f := range s.Files {
			fp := filepath.Join(skillsDir, s.Name, f.RelPath)
			if err := util.WriteFile(fp, f.Content); err != nil {
				return nil, util.Wrap(err, "write %s", fp)
			}
			written = append(written, fp)
		}
	}

	return written, nil
}

func buildKiroAgentsMd(ctx Context) string {
	var b strings.Builder
	b.WriteString(buildContextBody(ctx))
	b.WriteString("---\n\n")
	b.WriteString("_Generated by switchic — re-run `switchic switch kiro` to update._  \n")
	b.WriteString("_Steering files in `.kiro/steering/`. Agent definitions in `.kiro/agents/`. Skills in `.kiro/skills/`._\n")
	return b.String()
}

// kiroAgentJSON is the JSON shape Kiro CLI expects for agent configuration files.
type kiroAgentJSON struct {
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	Prompt           string      `json:"prompt,omitempty"`
	Tools            []string    `json:"tools,omitempty"`
	ToolAliases      interface{} `json:"toolAliases,omitempty"`
	AllowedTools     []string    `json:"allowedTools,omitempty"`
	ToolsSettings    interface{} `json:"toolsSettings,omitempty"`
	Resources        interface{} `json:"resources,omitempty"`
	Model            string      `json:"model,omitempty"`
	McpServers       interface{} `json:"mcpServers,omitempty"`
	IncludeMcpJson   *bool       `json:"includeMcpJson,omitempty"`
	Hooks            interface{} `json:"hooks,omitempty"`
	WelcomeMessage   string      `json:"welcomeMessage,omitempty"`
	KeyboardShortcut string      `json:"keyboardShortcut,omitempty"`
}

func buildKiroAgentFile(a agent.Definition) ([]byte, error) {
	obj := kiroAgentJSON{
		Name:        a.Name,
		Description: collapseNewlines(a.Description),
		Prompt:      a.Instructions,
	}
	if k := a.Kiro; k != nil {
		obj.Tools = k.Tools
		obj.ToolAliases = k.ToolAliases
		obj.AllowedTools = k.AllowedTools
		obj.ToolsSettings = k.ToolsSettings
		obj.Resources = k.Resources
		obj.Model = k.Model
		obj.McpServers = k.McpServers
		obj.IncludeMcpJson = k.IncludeMcpJson
		obj.Hooks = k.Hooks
		obj.WelcomeMessage = k.WelcomeMessage
		obj.KeyboardShortcut = k.KeyboardShortcut
	}
	return json.MarshalIndent(obj, "", "  ")
}

// buildKiroSteeringFile renders a rules.Definition into a Kiro steering file
// (.kiro/steering/<name>.md). The frontmatter keys follow Kiro's camelCase
// naming (fileMatchPattern, etc.) regardless of the snake_case YAML tags used
// in the rule definition.
func buildKiroSteeringFile(r rules.Definition) ([]byte, error) {
	var b strings.Builder

	// ── frontmatter ───────────────────────────────────────────────────────────
	b.WriteString("---\n")

	inclusion := "always" // default
	if r.Kiro != nil && r.Kiro.Inclusion != "" {
		inclusion = r.Kiro.Inclusion
	}
	fmt.Fprintf(&b, "inclusion: %s\n", inclusion)

	switch inclusion {
	case "fileMatch":
		if r.Kiro != nil && r.Kiro.FileMatchPattern != nil {
			var patterns []string
			switch v := r.Kiro.FileMatchPattern.(type) {
			case string:
				patterns = []string{v}
			case []any:
				for _, item := range v {
					if s, ok := item.(string); ok {
						patterns = append(patterns, s)
					}
				}
			}
			switch len(patterns) {
			case 0:
				// nothing to emit
			case 1:
				fmt.Fprintf(&b, "fileMatchPattern: %q\n", patterns[0])
			default:
				quoted := make([]string, len(patterns))
				for i, p := range patterns {
					quoted[i] = fmt.Sprintf("%q", p)
				}
				fmt.Fprintf(&b, "fileMatchPattern: [%s]\n", strings.Join(quoted, ", "))
			}
		}
	case "auto":
		if r.Kiro != nil {
			if r.Kiro.Name != "" {
				fmt.Fprintf(&b, "name: %s\n", r.Kiro.Name)
			}
			if r.Kiro.Description != "" {
				fmt.Fprintf(&b, "description: %s\n", r.Kiro.Description)
			}
		}
	}

	b.WriteString("---\n\n")

	// ── body ──────────────────────────────────────────────────────────────────
	fmt.Fprintf(&b, "# %s\n\n", r.Name)
	if r.Description != "" {
		fmt.Fprintf(&b, "%s\n\n", r.Description)
	}
	if r.Content != "" {
		b.WriteString(r.Content)
		if !strings.HasSuffix(r.Content, "\n") {
			b.WriteString("\n")
		}
	}
	return []byte(b.String()), nil
}

// buildKiroSkillFile renders a skill.Definition into a Kiro SKILL.md.
func buildKiroSkillFile(s skill.Definition) (string, error) {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", s.Name)
	if s.Description != "" {
		fmt.Fprintf(&b, "description: %s\n", collapseNewlines(s.Description))
	}
	if k := s.Kiro; k != nil {
		if k.License != "" {
			fmt.Fprintf(&b, "license: %s\n", k.License)
		}
		if k.Compatibility != "" {
			fmt.Fprintf(&b, "compatibility: %s\n", k.Compatibility)
		}
		if k.AllowedTools != "" {
			fmt.Fprintf(&b, "allowed-tools: %s\n", k.AllowedTools)
		}
		if k.Metadata != nil {
			raw, err := yaml.Marshal(map[string]interface{}{"metadata": k.Metadata})
			if err != nil {
				return "", fmt.Errorf("marshal kiro skill metadata %s: %w", s.Name, err)
			}
			b.Write(raw)
		}
	}
	b.WriteString("---\n\n")
	if s.Prompt != "" {
		b.WriteString(s.Prompt)
		if !strings.HasSuffix(s.Prompt, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String(), nil
}
